- name: Ensure GCP repo file exists and modify it if necessary
  hosts: all
  tasks:
    - name: Check GCP repo file exist
      stat:
        path: /etc/yum.repos.d/google-cloud.repo
      register: gcp_repo_exist
      become: yes

    - name: Disable GPG check in GCP repo file
      ansible.builtin.replace:
        path: /etc/yum.repos.d/google-cloud.repo
        regexp: 'repo_gpgcheck=1'
        replace: 'repo_gpgcheck=0'
      when: gcp_repo_exist.stat.exists
      become: yes

    - name: Remove incorrect NodeSource GPG key
      file:
        path: /etc/pki/rpm-gpg/NODESOURCE-NSOLID-GPG-SIGNING-KEY-EL
        state: absent
      become: yes

    - name: Import correct NodeSource GPG key
      rpm_key:
        state: present
        key: https://rpm.nodesource.com/pub/el/NODESOURCE-GPG-SIGNING-KEY-EL
      become: yes

    - name: Download NodeSource RPM
      shell: 'yum install https://rpm.nodesource.com/pub_20.x/nodistro/repo/nodesource-release-nodistro-1.noarch.rpm -y'
      become: yes
      ignore_errors: yes

    - name: Install Node.js from NodeSource
      yum:
        name: nodejs
        state: present
        enablerepo: nodesource
        disable_gpg_check: no
      args:
        setopt:
          - nodesource-nodejs.module_hotfixes=1
      become: yes

    - name: Install build essentials for native modules
      yum:
        name: gcc-c++
        state: present
      become: yes